apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kuber1-deployment
  labels:
    app: docker-kuber1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-kuber1
  template:
    metadata:
      labels:
        app: docker-kuber1
    spec:
      containers:
      - name: docker-kuber1
        image: shravyadockerid/docker-demo1:firstImage
        
        ports: 
        - containerPort: 8081  
---        
apiVersion: v1
kind: Service
metadata:
  name: docker-demo1-service
  labels:
    name: docker-demo1-service
spec:
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    app: docker-demo1
  type: LoadBalancer
                